// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAiUlJvHnHghZzZGamnyRQtbeQOTBcXL4',
    appId: '1:84276786320:web:d1ec92eda3da735bf35415',
    messagingSenderId: '84276786320',
    projectId: 'empireapp-2a997',
    authDomain: 'empireapp-2a997.firebaseapp.com',
    storageBucket: 'empireapp-2a997.appspot.com',
    measurementId: 'G-3KZ757XYYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApluchq6b6yQxUZZbCX4RmlSvIudTClE0',
    appId: '1:84276786320:android:0e433c7fea8f75def35415',
    messagingSenderId: '84276786320',
    projectId: 'empireapp-2a997',
    storageBucket: 'empireapp-2a997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdevqlrAg1hm83wpbQltW-uesOr7AUlA',
    appId: '1:84276786320:ios:859092d780a4798df35415',
    messagingSenderId: '84276786320',
    projectId: 'empireapp-2a997',
    storageBucket: 'empireapp-2a997.appspot.com',
    iosBundleId: 'com.example.empireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdevqlrAg1hm83wpbQltW-uesOr7AUlA',
    appId: '1:84276786320:ios:859092d780a4798df35415',
    messagingSenderId: '84276786320',
    projectId: 'empireapp-2a997',
    storageBucket: 'empireapp-2a997.appspot.com',
    iosBundleId: 'com.example.empireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAiUlJvHnHghZzZGamnyRQtbeQOTBcXL4',
    appId: '1:84276786320:web:e970d5cbcd1f111ff35415',
    messagingSenderId: '84276786320',
    projectId: 'empireapp-2a997',
    authDomain: 'empireapp-2a997.firebaseapp.com',
    storageBucket: 'empireapp-2a997.appspot.com',
    measurementId: 'G-2X1Z1GMXHF',
  );
}
